In [1]:
import numpy as np

In [5]:
w = np.random.rand(4, 3)
w

array([[0.50952157, 0.89836167, 0.33013076],
       [0.15904111, 0.40594037, 0.84785167],
       [0.20229651, 0.85862379, 0.06296595],
       [0.86488059, 0.44205065, 0.2514135 ]])

In [6]:
x = np.random.rand(3, 1)
x

array([[0.77717801],
       [0.26003401],
       [0.43731454]])

In [8]:
np.dot(w, x)

array([[0.77396452],
       [0.59993942],
       [0.40802771],
       [0.89706115]])

In [2]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)

In [3]:
B.shape

(4, 1)

In [4]:
B

array([[-1.99568753],
       [ 0.70649198],
       [ 0.29464731],
       [-0.08929263]])