In [2]:
import numpy as np
import random

In [5]:
w = np.random.rand(4, 3)
w

array([[0.50952157, 0.89836167, 0.33013076],
       [0.15904111, 0.40594037, 0.84785167],
       [0.20229651, 0.85862379, 0.06296595],
       [0.86488059, 0.44205065, 0.2514135 ]])

In [6]:
x = np.random.rand(3, 1)
x

array([[0.77717801],
       [0.26003401],
       [0.43731454]])

In [8]:
np.dot(w, x)

array([[0.77396452],
       [0.59993942],
       [0.40802771],
       [0.89706115]])

In [2]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)

In [3]:
B.shape

(4, 1)

In [4]:
B

array([[-1.99568753],
       [ 0.70649198],
       [ 0.29464731],
       [-0.08929263]])

In [8]:
np.random.randint(0, 10, size=(2, 3))

array([[3, 5, 3],
       [4, 1, 1]])

In [16]:
def addition(x, y):
    print(x+y)
    
listOne = [1, 2, 3, 4, 5]
listTwo = [2, 3, 4, 5, 6]

result = map(addition, listOne, listTwo)

#print(type(result))
flag = 0
print(result)

list(result)

3
5
7
9
11


[None, None, None, None, None]

In [24]:
x = np.random.randint(1, 10, size=(5, 3))
w = np.random.randint(1, 10, size=(5, 1))

print(x, "\n\n\n", w)
np.dot(w.T, x)

[[9 5 1]
 [2 8 4]
 [4 4 7]
 [6 4 1]
 [9 4 1]] 


 [[2]
 [4]
 [3]
 [7]
 [3]]


array([[107,  94,  49]])

In [25]:
18 + 8 + 12 + 42 + 27

107

In [31]:
a1 = np.random.randint(0, 10, size=(3, 2, 4))
a2 = np.random.randint(0, 10, size=(3, 2, 4))

print(a1)
print(a1.shape)

aSum = np.sum(a1, axis=1)
print(aSum)
aSum.shape

[[[4 4 4 6]
  [3 5 2 8]]

 [[2 4 5 4]
  [4 7 8 2]]

 [[4 4 6 6]
  [9 1 3 9]]]
(3, 2, 4)
[[ 7  9  6 14]
 [ 6 11 13  6]
 [13  5  9 15]]


(3, 4)

In [33]:
aaSum = np.sum(aSum, axis=1)
print(aaSum)
aaSum.shape

[36 36 42]


(3,)