In [2]:
import numpy as np

In [4]:
print(np.random.seed(1))

None


In [10]:
arr = np.zeros((3, 5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
len(arr)

3

In [12]:
arr1 = np.array([[1, 2],
                [2, 3],
                [5, 6]])
print(arr1)

[[1 2]
 [2 3]
 [5 6]]


In [14]:
arr2 = np.array([[1, 2, 3]])
print(arr2)

[[1 2 3]]


In [15]:
np.dot(arr2, arr1)

array([[20, 26]])