In [1]:
import numpy as np

In [19]:
arr1 = np.random.rand(4, 3) * 10
arr2 = np.random.rand(3, 2) * 10
print(arr1,"\n\n\n", arr2)

[[0.65973071 5.07577151 1.25994188]
 [4.13516593 5.53287576 9.63657283]
 [7.05062748 8.5757182  4.09453489]
 [3.50875331 3.1941478  8.4656868 ]] 


 [[3.47679732 9.67693766]
 [3.65020481 7.93422033]
 [0.9713191  0.58884287]]


In [20]:
arr1.T

array([[0.65973071, 4.13516593, 7.05062748, 3.50875331],
       [5.07577151, 5.53287576, 8.5757182 , 3.1941478 ],
       [1.25994188, 9.63657283, 4.09453489, 8.4656868 ]])

In [25]:
arr1.size

12

In [18]:
np.dot(arr1, arr2)

array([[1.38876557, 1.76923399],
       [1.18190986, 1.55822962]])

In [21]:
np.transpose(arr1) + 1

array([[1.98349175, 1.87612857],
       [1.78314298, 1.88762465],
       [1.83209193, 1.47910331]])

In [29]:
x = np.array([[0, 3, 4], [2, 6, 4]])
print(x)
x_ = np.linalg.norm(x,axis=1,keepdims=True)

[[0 3 4]
 [2 6 4]]


In [30]:
x / x_

array([[0.        , 0.6       , 0.8       ],
       [0.26726124, 0.80178373, 0.53452248]])

In [31]:
np.sum(x)

19